apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: eu-west-2
    failure-domain.beta.kubernetes.io/zone: eu-west-2a
  name: pvc-d186c2ed-44d1-4850-b1c2-46c2acc4df6e
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://eu-west-2a/vol-0bf4095787524cbcb
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: exchange-event-publisher-pvc
    namespace: master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - eu-west-2a
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - eu-west-2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-retain
  volumeMode: Filesystem
