apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: exchange-event-publisher
  name: exchange-event-publisher-pvc
  namespace: master
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: aws-retain
  volumeMode: Filesystem
  volumeName: pvc-d186c2ed-44d1-4850-b1c2-46c2acc4df6e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
